# fly.toml app configuration file generated for clini on 2024-05-03T21:15:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clini'
primary_region = 'sea'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_DEBUG = 'true'
  APP_ENV = 'production'
  APP_FAKER_LOCALE = 'es_AR'
  APP_FALLBACK_LOCALE = 'en'
  APP_LOCALE = 'es'
  APP_MAINTENANCE_DRIVER = 'file'
  APP_MAINTENANCE_STORE = 'database'
  APP_NAME = 'Clini'
  APP_SERVICE = 'clini'
  APP_TIMEZONE = 'UTC'
  APP_URL = 'https://clini.fly.dev'
  BCRYPT_ROUNDS = '12'
  CACHE_PREFIX = ''
  CACHE_STORE = 'database'
  DB_CONNECTION = 'mysql'
  DB_DATABASE = 'railway'
  DB_USERNAME = 'root'
  FILESYSTEM_DISK = 'local'
  FRONTEND_URL = 'https://clini.fly.dev'
  LOG_CHANNEL = 'stderr'
  LOG_DEPRECATIONS_CHANNEL = 'null'
  LOG_LEVEL = 'info'
  LOG_STACK = 'single'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  MEMCACHED_HOST = '127.0.0.1'
  QUEUE_CONNECTION = 'database'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  VITE_API_URL = 'https://clini.fly.dev/api'
  VITE_APP_NAME = '${APP_NAME}'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
